### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:7656

### ISSUE THREAD

**Issue by twkevinzhang** [redhog/node-i2p#4]
When I follow the  #Server usage in the README.md, I have the following error:

```node
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:7656
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
Emitted 'error' event on  instance at:
    at module.exports.handleError (C:\Project\test\node_modules\i2p\LineProtocol.js:91:8)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 7656
}
```

and #Client usage also raises the same error

How can I solve it? thx

**Comment by eyedeekay** [comment]
You need to enable SAM. Go to http://localhost:7657/configclients and start the SAM bridge, or enable it to run by default.
